name: Testy jednostkowe

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Klonowanie repozytorium
        uses: actions/checkout@v3

      - name: Instalacja Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygame  # jeśli używasz pygame

      - name: Uruchomienie testów
        run: |
          python -m unittest discover -s tests
